onlyBuiltDependencies:
  - '@firebase/util'
  - protobufjs
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@firebase/util': true
  protobufjs: true
  unrs-resolver: true
overrides:
  'postcss@<8.5.18': 8.5.18
  'protobufjs@<7.6.5': 7.6.5
  'sharp@<0.35.0': 0.35.0
  'socket.io-parser@<4.2.7': 4.2.7
  'websocket-driver@<0.7.5': 0.7.5
  'ws@>=8.0.0 <8.21.0': 8.21.0
